/*
 *  APFortunes.h
 *  FortuneCookie
 *
 *  Created by Scott Penberthy on 2/10/10.
 *  Copyright 2010 __MyCompanyName__. All rights reserved.
 *
 */

#define kFortuneCount 441
#define kFontCount 6

static char* kFortunes[] = {
	"He who climbs a ladder must begin at the first step.",
	"The one who snores will always fall asleep first.",
	"Let your heart make your decisions - it does not get as confused as your head.",
	"See the light at the end of the tunnel.",
	"For true love? Send real roses preserved in 24kt gold!",
	"Everyone agrees you are the best.",
	"Your dynamic eyes have attracted a secret admirer.",
	"Life is a verb",
	"You are offered the dream of a lifetime. Say yes!",
	"Life to you is a dashing and bold adventure",
	"What's vice today may be virtue tomorow.",
	"Your co-workers take pleasure in your great sense of creativity.",
	"Keep true to the dreams of your youth.",
	"The human spirit is stronger than anything that can happen to it.",
	"It is much easier to be cirtical than to be correct.",
	"Do not upset the penguin today.",
	"I am a fortune. You just broke my little house. Where will i live now?",
	"Nothing is as good or bad as it appears.",
	"Customer service is like taking a bath you have to keep doing it.",
	"Everything will now come your way.",
	"Perhaps you've been focusing too much on that one thing..",
	"It takes ten times as many muscles to frown as it does to smile.",
	"Listen to yourself more often",
	"You are always welcome in any gathering.",
	"Old dreams never die they just get filed away.",
	"Judge not according to the appearance.",
	"Happiness isn't something you remember, it's something you experience.",
	"A good time to finish up old tasks.",
	"Eat something you never tried before.",
	"In the eyes of lovers, everything is beautiful.",
	"Be most affectionate today.",
	"Well-arranged time is the surest sign of a well-arranged mind.",
	"Nothing in the world is accomplished without passion.",
	"Traveling more often is important for your health and happiness.",
	"Pick a path with heart.",
	"The leader seeks to communicate his vision to his followers.",
	"Don't 'face' reality, let it be the place from which you leap.",
	"You love peace",
	"You are given the chance to take part in an exciting adventure.",
	"Fear is just excitement in need of an attitude adjustment.",
	"Treasure what you have.",
	"This is really a lovely day. Congratulations!",
	"A new outlook brightens your image and brings new friends.",
	"It takes more then good memory to have good memories.",
	"The smart thing to do is to begin trusting your intuitions.",
	"He who climbs a ladder must begin at the first step",
	"You are not a person who can be ignored.",
	"You are one of the people who \"goes places in life.\"",
	"You will have a bright future.",
	"The best way to give credit is to give it away.",
	"You will always get what you want through your charm and personality.",
	"Face facts with dignity.",
	"Shoot for the moon! If you miss you will still be amongst the stars.",
	"Do you believe? Endurance and persistence will be rewarded.",
	"Tell them what you really think. Otherwise, nothing will change.",
	"You are far more influential than you think.",
	"Go confidently in the direction of your dreams.",
	"When you get something for nothing, you just haven't been billed for it yet.",
	"Don't just spend time, invest it.",
	"It's kind of fun to do the impossible",
	"Don't cry.",
	"Be patient: in time, even an egg will walk.",
	"Accept yourself",
	"One who admires you greatly is hidden before your eyes.",
	"The majority of the word \"can't\" is can.",
	"A well-aimed spear is worth three.",
	"Your many hidden talents will become obvious to those around you.",
	"A cheerful message is on its way to you.",
	"Your ability to pick a winner will bring you success.",
	"You are very grateful for the small pleasures of life.",
	"Believing is doing.",
	"You like Chinese food.",
	"Old friends, old wines and old gold are best",
	"Oops... Wrong cookie.",
	"Humor usually works at the moment of awkwardness.",
	"Meet your opponent half way. You need the exercise.",
	"Life is too short to waste time hating anyone.",
	"Your succeess will astonish everyone.",
	"Keep your plans secret for now.",
	"It takes more than good memory to have good memories.",
	"A thrilling time is in store for you.",
	"The time is right to make new friends.",
	"You will enjoy good health, you will be surrounded by luxury",
	"You have a curious smile and a mysterious nature",
	"Human invented language to satisfy the need to complain.",
	"Go ask your mom.",
	"Take it easy",
	"It is better to have a hen tomorrow than an egg today.",
	"Open up your heart - it can always be closed again.",
	"Only talent people get help  from others.",
	"You always know the right times to be assertive or to simply wait.",
	"I am a bad luck person since I was born",
	"Others enjoy your company.",
	"You have a curious smile and a mysterious nature.",
	"Judge each day not by the harvest you reap but by the seeds you plant.",
	"When you can't naturally feel upbeat it can sometimes help you to act as if you did.",
	"Great thoughts come from the heart.",
	"Be a generous friend and a fair enemy",
	"Love because it is the only true adventure.",
	"Never quit!",
	"You are cautious in showing your true self to others.",
	"You will be traveling and coming into a fortune.",
	"Happiness is not the absence of conflict, but the ability to cope with it.",
	"When you can't naturally feel upbeat, it can sometimes help to act a if you did.",
	"Don't bother looking for fault. The reward for finding it is low.",
	"A man without aim is like a clock without hands, as useless if it turns as if it stands.",
	"Service is the rent we pay for the privilege of living on this planet.",
	"Use your talents. That's what they are intended for.",
	"Reading to the mind is what exercise is to the body.",
	"We cannot change the direction of the wind, but we can adjust our sails.",
	"When you're about to turn your heart into a stone remember: you do not walk alone.",
	"Everybody feels lucky for having you as a friend.",
	"The secret of getting ahead is getting started.",
	"Hard words break no bones, fine words butter no parsnips.",
	"People who are late are often happier than those who have to wait for them",
	"The possibility of a career change is near.",
	"Everything has beauty but not everyone sees it.",
	"Accept what comes to you each day.",
	"An understanding heart warms all that are graced with it's presense.",
	"The race is not always to the swift, but to those who keep on running.",
	"Your problem just became your stepping stone.  Catch the moment.",
	"In human endeavor, chance favors the prepared mind.",
	"When the moment comes, take  the top one.",
	"Dream your dream and your dream will dream of you.",
	"Listen to life, and you will hear the voice of life crying, Be!",
	"Use your instincts now.",
	"Did you remember to order your take out also?",
	"A pleasant surprise is in store for you tonight.",
	"Compassion will cure more then condemnation.",
	"Those grapes you cannot taste are always sour.",
	"You will win success in whatever you adopt.",
	"Adjust finances, make budgets, to improve your standing.",
	"You  are  contemplating  some  action  which will bring credit upon you",
	"Try everything once, even the things you don't think you will like.",
	"You have a reputation for being straightforward and honest.",
	"You are a person of strong sense of duty",
	"Think of how you can assist on a problem, not who to blame.",
	"Before you wonder \"Am I doing things right,\" ask \"Am I doing the right things?\"",
	"You have a strong desire for a home and your family interests come first.",
	"Your secret desire to completely change your life will manifest.",
	"The gambler is like the fisherman both have beginners luck.",
	"Change your thoughts and you change the world.",
	"Smile. Tomorrow is another day.",
	"May you have great luck.",
	"Put your mind into planning today. Look into the future.",
	"Bad luck and ill misfortune will infest your pathetic soul for all eternity.",
	"Working out the kinks today will make for a better tomorrow.",
	"Do not be overly judgemental of your loved one's intentions or actions.",
	"Great works are performed not by strength, but by perseverance.",
	"The eyes believe themselves; the ears believe other people.",
	"Wow! A secret message from you teeth!",
	"Constant grinding can turn an iron nod into a needle.",
	"The joyful energy of the day will have a positive affect on you.",
	"You will soon be surrounded by good friends and laughter.",
	"All troubles you have can pass away very quickly.",
	"It's the worst of times, you need to summon your optimism.",
	"Enjoy life! It is better to be happy than wise.",
	"You will be selected for a promotion because of your accomplishments.",
	"The best is yet to come.",
	"You will travel to many places.",
	"You don't get harmony when everyone sings the same note.",
	"We all have extraordinary coded within us, waiting to be released.",
	"The troubles you have now will pass away quickly.",
	"Someone close to you is waiting for you to call.",
	"The secret of staying young is good health and lying about your age.",
	"Good beginning is half done.",
	"A truly great person never puts away the simplicity of a child.",
	"Anything you do, do it well. The last thing you want is to be sorry for what you didn't do.",
	"Sing and rejoice, fortune is smiling on you.",
	"Keep your eyes open. You never know what you might see.",
	"Keep your feet on the ground even though friends flatter you.",
	"The food here taste so good, even a cave man likes it.",
	"It may be those who do most, dream most",
	"Stop procrastinating - starting tomorrow",
	"Some pursue happiness; you create it.",
	"If you want the rainbow, then you have to tolerate the rain.",
	"Life is too short to hold grudges.",
	"You should be able to undertake and complete anything",
	"A virtual fortune cookie will not satisfy your hunger like that of a home made one.",
	"Friends long absent are coming back to you.",
	"Take the chance while you still have the choice.",
	"Present your best ideas today to an eager and welcoming audience.",
	"love thy neighbour, just don't get caught",
	"Fortune smiles upon you today.",
	"Action speaks nothing, without the Motive.",
	"you cant go down the right path with out first discovering the path to go down",
	"Money will come to you when you are doing the right thing.",
	"Perhaps you've been focusing too much on spending.",
	"Integrity is the essense of everything successful.",
	"You should be able to make money and hold on to it.",
	"A golden egg of opportunity falls into your lap this month.",
	"Compassion is a way of being.",
	"A kind word will keep someone warm for years.",
	"The greatest precept is continual awareness.",
	"All the world may not love a lover but they will be watching him.",
	"We cannot direct the wind but we can adjust the sails.",
	"The pleasure of what we enjoy is lost by wanting more",
	"Soon you will be sitting on top of the world.",
	"The important thing is to never stop questioning.",
	"If your desires are not extravagant, they will be granted",
	"You are never selfish with your advice or your help.",
	"You have a great capability to break cookies - use it wisely!",
	"The best things in life aren't things.",
	"You have a quiet and unobtrusive nature.",
	"The human spirit is stronger then anything that can happen to it.",
	"Never bring unhappy feelings into your home.",
	"You can never been certain of success, but you can be certain of failure if you never try.",
	"Any decision you have to make tomorrow is a good decsion.",
	"Your emotional currents are flowing powerfully now.",
	"Time may fly by. But Memories don't.",
	"Enthusiastic leadership gets you a promotion when you least expect it.",
	"Your skill will accomplish what the force of many cannot.",
	"Today is the tomorrow we worried about yesterday",
	"Trust your intuition. The universe is guiding your life.",
	"The life of every woman or man - the heart of it - is pure and holy joy.",
	"Your dream will come true when you least expect it.",
	"Many folks are about as happy as they make up their minds to be.",
	"you will spend old age in confort and material wealth",
	"A small lucky package is on its way to you soon.",
	"You will overcome difficult times.",
	"Teamwork: the fuel that allows common people attain uncommon results.",
	"Give yourself some peace and quiet for at least a few hours.",
	"Your life becomes more and more of an adventure!",
	"Use your head, but live in your heart.",
	"Here we go. \"Moo Shu Cereal\" for breakfast with duck sauce.",
	"A new wardrobe brings great joy and change in your life.",
	"Do not hesitate to look for help, an extra hand should always be welcomed.",
	"An unexpected aquaintance will resurface.",
	"Traveling this year will bring your life into greater perspective.",
	"The big issues are work, career, or status right now.",
	"Dogs have owners, cats have staff.",
	"You will recieve a gift from someone that cares about you.",
	"You will be called to fill a position of high honor and responsibility.",
	"Make all you can, save all you can, give all you can.",
	"Your passions sweep you away.",
	"You will be sharing great news with all people you love",
	"It's tough to be fascinating.",
	"Soon life will become more interesting",
	"Being alone and being lonely are two different things.",
	"The early bird gets the worm, but the second mouse gets the cheese.",
	"Q. What is H2O? A. Caring, 2 parts Hug and 1 part Open-mind.",
	"Be calm when confronting an emergency crisis.",
	"Being happy is not always being perfect.",
	"Your ability to accomplish tasks will follow with success.",
	"The expanse of your intelligence is a void no universe could ever fill.",
	"There is always a way - if you are committed.",
	"Working hard will make you live a happy life.",
	"All the preparation you've done will finally be paying off!",
	"You will be successful in your work",
	"Warning, do not eat your fortune.",
	"When in doubt, let your instincts guide you.",
	"Laughter is the shortest distance between two people.",
	"You can fix it with a little extra energy and a positive attitude.",
	"Love is on its way.",
	"You are not illiterate.",
	"An alien of some sort will be appearing to you shortly!",
	"It is better to be the hammer then the anvil.",
	"To make the cart go, you must grease the wheels.",
	"You are the man of righteousness and integrity.",
	"No matter what your past has been, you have a spotless future.",
	"You are vigorous in words and action.",
	"Next time you have the opportunity, go on a rollercoaster.",
	"Broke is only temporary, poor is a state of mind.",
	"The simplest answer is to act.",
	"For hate is never conquered by hate. Hate is conquered by love.",
	"To courageously shoulder the responsibility of one's mistake is character.",
	"Be direct, usually one can accomplish more that way.",
	"Grant yourself a wish this year only you can do it.",
	"You need to live authentically, and you can't ignore that.",
	"Luck sometimes visits a fool, but it never sits down with him.",
	"A new friend helps you break out of an old routine.",
	"Humor is an affirmation of dignity",
	"To build a better world, start in your community.",
	"There are many new opportunities that are being presented to you.",
	"Tomorrow, take a moment to do something just for yourself.",
	"The wise are aware of their treasure, while fools follow their vanity",
	"Live each day well and wisely",
	"You love Chinese food.",
	"Questions provide the key to unlocking our unlimited potential.",
	"You will always have good luck in your personal affairs.",
	"Impossible standards just make life difficult.",
	"You have an unusually magnetic personality.",
	"You are contemplating some action which will bring credit upon you.",
	"today you should be a passenger. Stay close to a driver for a day.",
	"Every Friend Joys in your Success",
	"Sometimes the object of the journey is not the end, but the journey itself.",
	"A different world cannot be build by indifferent people.",
	"How can you have a beautiful ending without making beautiful mistakes?",
	"You may be hungry soon: order a takeout now.",
	"Excuses are easy to manufacture, and hard to sell.",
	"Don't find fault, find a remedy",
	"You'll advance for with your abilities.",
	"A pleasant surprise is waiting for you.",
	"Life  always gets harder near the summit.",
	"I have a dream.... Time to go to bed.",
	"Never cut what you can untie.",
	"Sometimes travel to new places leads to great transformation.",
	"There are no shortcuts to any place worth going",
	"Demonstrate refinement in everything you do.",
	"Spring has sprung. Life is blooming.",
	"You will enjoy razon-sharp spiritual vision today.",
	"A warm smile is testimony of a generous nature.",
	"A secret admirer will soon send you a sign of affection.",
	"Love asks me no questions, and gives me endless support. Shakespeare",
	"In the end there are three things that last: faith, hope and love; and the greatest of these is love.",
	"Don't forget, you are always on our minds.",
	"Love is for the lucky and the brave.",
	"If you continually give, you will continually have.",
	"If you want the rainbow, you must put up with the rain. D. Parton",
	"If you would be loved, love and be lovable.",
	"The one you love is closer than you think.",
	"Love always and deeply.",
	"Your heart will always make itself known through your words.",
	"Love begets love.",
	"We cannot do great things; only small things with great love. Mother Teresa",
	"Love is like wildflowers...it is often found in the most unlikely places.",
	"Love is the only medicine for a broken heart.",
	"Love is the triumph of imagination over intelligence. H.L. Mencken",
	"Much more grows in the garden than that which is planted there.",
	"Only love lets us see normal things in an extraordinary way.",
	"The greatest gift is love.",
	"There is no limit to love's forbearance, to its trust, its hope, its power to endure.",
	"Those who have love, have wealth beyond measure.",
	"To love is to forgive.",
	"Hearts are not to be had as a gift, hearts are to be earned. W.B. Yeats",
	"Your heart is a place to draw true happiness.",
	"Love conquers all.",
	"Count your blessings by thinking of those whom you love.",
	"There is a true and sincere friendship between you and your friends.",
	"You find beauty in ordinary things, do not lose this ability.",
	"Ideas are like children; there are none so wonderful as your own.",
	"A thrilling time is in your immediate future.",
	"Your blessing is no more than being safe and sound for the whole lifetime.",
	"Plan for many pleasures ahead.",
	"The joyfulness of a man prolongeth his days.",
	"Your everlasting patience will be rewarded sooner or later.",
	"Make two grins grow where there was only a grouch before.",
	"Something you lost will soon turn up.",
	"Your heart is pure, and your mind clear, and your soul devout.",
	"Excitement and intrigue follow you closely wherever you go!",
	"A pleasant surprise is in store for you.",
	"May life throw you a pleasant curve.",
	"As the purse is emptied the heart is filled.",
	"Be mischievous and you will not be lonesome.",
	"You have a deep appreciation of the arts and music.",
	"Your flair for the creative takes an important place in your life.",
	"Your artistic talents win the approval and applause of others.",
	"Pray for what you want, but work for the things you need.",
	"Your greatest fortune is the large number of friends you have.",
	"A firm friendship will prove the foundation on your success in life.",
	"Don't ask, don't say. Everything lies in silence.",
	"Look for new outlets for your own creative abilities.",
	"Be prepared to accept a wondrous opportunity in the days ahead!",
	"Fame, riches and romance are yours for the asking.",
	"Good luck is the result of good planning.",
	"Good things are being said about you.",
	"Smiling often can make you look and feel younger.",
	"Someone is speaking well of you.",
	"You will inherit some money or a small piece of land.",
	"Your life will be happy and peaceful.",
	"A friend is a present you give yourself.",
	"A member of your family will soon do something that will make you proud.",
	"A quiet evening with friends is the best tonic for a long day.",
	"A single kind word will keep one warm for years.",
	"Anger begins with folly, and ends with regret.",
	"Generosity and perfection are your everlasting goals.",
	"Happy news is on its way to you.",
	"Little and often makes much.",
	"The days you work are the best days.",
	"Today is a lucky day for those who remain cheerful and optimistic.",
	"You were born with the skill to communicate with people easily.",
	"The hard times will begin to fade, joy will take their place.",
	"The first step to better times is to imagine them.",
	"When you speak honestly and openly, others truly listen to you.",
	"It doesn't matter. Who is without a flaw?",
	"It is much wiser to take advice than to give it.",
	"Many a false step is made by standing still.",
	"The skills you have gathered will one day come in handy.",
	"Every excess becomes a vice.",
	"Keep in close touch with what your competition is doing.",
	"Your talents will be recognized and suitably rewarded.",
	"He who laughs at himself never runs out of things to laugh at.",
	"If your desires are not extravagant they will be granted.",
	"Let there be magic in your smile and firmness in your handshake.",
	"If you want the rainbow, you must to put up with the rain. D. Parton",
	"Nature, time and patience are the three best physicians.",
	"Strong and bitter words indicate a weak cause.",
	"The beginning of wisdom is to desire it.",
	"You will have a very pleasant experience.",
	"You will live a long, happy life.",
	"You will spend old age in comfort and material wealth.",
	"You will step on the soil of many countries.",
	"You will take a chance in something in the near future.",
	"You will witness a special ceremony.",
	"Your great attention to detail is both a blessing and a curse.",
	"Your ability to juggle many tasks will take you far.",
	"A friend asks only for your time, not your money.",
	"You will be invited to an exciting event.",
	"Our first and last love...is self love.",
	"None of the secrets of success will work unless you do.",
	"Your happiness is intertwined with your outlook on life.",
	"Decide what you want and go for it.",
	"Your past success will be overshadowed by your future success.",
	"You are talented in many ways.",
	"Any rough times are behind you.",
	"Grand adventures await those who are willing to turn the corner.",
	"The smart thing is to prepare for the unexpected.",
	"There is yet time enough for you to take a different path.",
	"You are very expressive and positive in words, act and feeling.",
	"You should be able to undertake and complete anything.",
	"A journey of a thousand miles begins with a single step. Lao Tzu",
	"A scholars ink lasts longer than a martyrs blood.",
	"Funny thing about humility. Just when you think you've got it, you've lost it.",
	"You can always find happiness at work on Friday.",
	"All your hard work will soon pay off.",
	"Do not mistake temptation for opportunity.",
	"You will be fortunate in everything you put your hands to.",
	"You will have gold pieces by the bushel.",
	"Put the data you have uncovered to beneficial use.",
	"Skill comes from diligence.",
	"Don't forget to do good deeds as you accumulate wealth.",
	"Your money worries are over! Your new job will bring you a huge increase in income.",
	"Avert misunderstanding by calm, poise and balance.",
	"Consolidate rather than expand business projects in the near future.",
	"Delay is the antidote for anger.",
	"Get ready! Good fortune comes in bunches.",
	"You will be wise not to seek too much from others",
	"He who throws dirt is losing ground.",
	"A woman who seeks to be equal with men lacks ambition. Ouch!!!",
	"The greatest danger could be your stupidity.",
	"He who laughs last is laughing at you.",
	"A closed mouth gathers no feet.",
	"A conclusion is simply the place where you got tired of thinking.",
	"A cynic is only a frustrated optimist.",
	"A fanatic is one who can't change his mind, and won't change the subject.",
	"The world may be your oyster, but it doesn't mean you'll get its pearl.",
	"Flattery will go far tonight.",
	"Think of mother's exhortations more.",
	"You will outdistance all your competitors.",
	"You may be disappointed if you fail, but you are doomed if you don't try.",
	"Rest is a good thing, but boredom is its brother."
};

